import type { Metadata } from "next";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const headerLinks = [
  {
    name: "Overview",
    linkTo: "/",
    active: true,
    border: true,
  },
  {
    name: "Product",
    linkTo: "product",
    active: false,
  },
  {
    name: "Sales",
    linkTo: "sales",
    active: false,
  },
  {
    name: "Earning",
    linkTo: "earning",
    active: false,
  },
]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <SidebarProvider>
          <AppSidebar />
          <main className="w-full">
            <div className="w-full flex justify-between items-center p-2">
              <div className="w-full flex justify-start items-center gap-6">
                <SidebarTrigger />
                {headerLinks.map((item, index) => {
                  return (
                    <Link href={"products"} key={index} >
                      <p className={` ${item.border && item.border ? 'border-l-[1px] border-gray-300 pl-6' : ""} ${item.active?"text-gray-700":"text-gray-400"}  hover:text-gray-600 text-sm`}>{item.name}</p>
                    </Link>
                  )
                })}
              </div>
              <div className="w-full flex justify-end items-center">
                <p className="">Ass</p>
              </div>
            </div>
            {children}
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
