import type { Metadata } from "next";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        {/* <div className="flex justify-start items-start w-full">
        <div className="flex justify-center items-center w-[300px]">
          Ass
        </div>
        <div className="flex justify-start items-start w-full">
        {children}
        </div>
        </div> */}
        <SidebarProvider>
      <AppSidebar />
      <main className="w-full">
        <div className="w-full bg-yellow-200 flex justify-between">

        <SidebarTrigger />
        <p className="bg-green-500">Ass</p>
        </div>
        {children}
      </main>
    </SidebarProvider>
      </body>
    </html>
  );
}
